author: Inácio Ferrarini
author_url: https://twitter.com/inacioferrarini
github_url: https://github.com/inacioferrarini/Login
root_url: https://inacioferrarini.github.io/Login/
module: Login
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'Login.xcworkspace', -scheme, 'Login-iOS']
